# Generated by Django 6.0.3 on 2026-04-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="網址代稱"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(max_length=300, verbose_name="簡短描述"),
                ),
                ("description", models.TextField(verbose_name="詳細描述")),
                ("date", models.DateTimeField(verbose_name="活動日期")),
                ("location", models.CharField(max_length=200, verbose_name="地點")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to="events/", verbose_name="封面圖片"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="精選"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "活動",
                "verbose_name_plural": "活動",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=300, verbose_name="副標題"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="hero/", verbose_name="圖片"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
            ],
            options={
                "verbose_name": "首頁輪播",
                "verbose_name_plural": "首頁輪播",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StoryPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="網址代稱"
                    ),
                ),
                ("summary", models.CharField(max_length=300, verbose_name="摘要")),
                ("content", models.TextField(verbose_name="內容")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="stories/", verbose_name="圖片"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("water_story", "水井故事"),
                            ("usr", "USR 成果"),
                            ("experience", "體驗活動"),
                            ("aiot", "智慧應用"),
                        ],
                        max_length=20,
                        verbose_name="分類",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="精選"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "故事文章",
                "verbose_name_plural": "故事文章",
                "ordering": ["-created_at"],
            },
        ),
    ]
