# Generated by Django 4.2 on 2026-05-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pond",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("species", models.CharField(default="Fish", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("measured_at", models.DateTimeField(db_index=True)),
                ("temperature", models.FloatField(help_text="Temperature in Celsius")),
                ("ph", models.FloatField(help_text="pH value")),
                ("dissolved_oxygen", models.FloatField(help_text="Dissolved oxygen in mg/L")),
                ("salinity", models.FloatField(blank=True, help_text="Salinity in ppt", null=True)),
                (
                    "pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="water.pond",
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_at"],
                "indexes": [models.Index(fields=["pond", "-measured_at"], name="water_senso_pond_id_746eaa_idx")],
            },
        ),
    ]
