# Generated by Django 6.0.3 on 2026-06-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("water", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorreading",
            name="ammonia",
            field=models.FloatField(
                blank=True, help_text="Ammonia (NH3) in mg/L", null=True
            ),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="nitrite",
            field=models.FloatField(
                blank=True, help_text="Nitrite (NO2-) in mg/L", null=True
            ),
        ),
    ]
